runner:
  train_data_dir: "/users/rongzhimai/Downloads/comp_0713/data/data205411/2023-cvr-contest-data/train_data"
  train_reader_path: "criteo_reader" # importlib format
  use_gpu: False
  use_auc: True
  train_batch_size: 512
  epochs: 1
  print_interval: 50
  model_save_path: "output_model_dnn_queue"

  thread_num: 1
  reader_type: "QueueDataset"  # DataLoader / QueueDataset / RecDataset
  pipe_command: "python3.7 queuedataset_reader.py"
  dataset_debug: False
  split_file_list: False

  infer_batch_size: 512
  infer_reader_path: "criteo_reader" # importlib format
  test_data_dir: "/users/rongzhimai/Downloads/comp_0713/data/data204194/test_data"
  infer_load_path: "output_model_dnn_queue"
  infer_start_epoch: 0
  infer_end_epoch: 1
# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  sparse_inputs_slots: 28
  sparse_feature_number: 88000000
  sparse_feature_dim: 9
  dense_input_dim: 13
  fc_sizes: [512, 256, 128, 32]
  distributed_embedding: 0
